//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HGU_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Specification()
        {
            this.Computers = new HashSet<Computers>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int id_Cpu { get; set; }
        public int id_Ram { get; set; }
        public int id_GraphicsAccelerator { get; set; }
        public int id_DataDrives { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Computers> Computers { get; set; }
        public virtual Cpu Cpu { get; set; }
        public virtual DataDrives DataDrives { get; set; }
        public virtual GraphicsAccelerator GraphicsAccelerator { get; set; }
        public virtual Ram Ram { get; set; }
    }
}
